version: "3.9"

services:
  lais-bot:
    build: .
    container_name: lais-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker_internal

networks:
  docker_internal:
    external: true
